# EMBEDDED SERVER CONFIGURATION
spring:
  data:
    mongodb.host: ${vcap.services.mongodb.credentials.host}
    mongodb.port: ${vcap.services.mongodb.credentials.port}
    mongodb.uri: ${vcap.services.mongodb.credentials.uri}
  activemq:
    broker-url: ${vcap.services.activemq.credentials.uri}
    user-queue: ${vcap.services.activemq.credentials.user.queue}
    cart-queue: ${vcap.services.activemq.credentials.cart.queue}
    order-queue: ${vcap.services.activemq.credentials.order.queue}
    notification-queue: ${vcap.services.activemq.credentials.notification.queue}
    account-queue: ${vcap.services.activemq.credentials.account.queue}
    sfaint-queue: ${vcap.services.activemq.credentials.sfaint.queue}
    default-queue: ${vcap.services.activemq.credentials.default.queue}
  account:
    userAuthString: PASSWORD/pctl/EMPLOYEE/Orangefeathers$$/pctl/EMPLOYEE
    enterPriseDetails: false/BMG/testEnterprise2@hotmail.com/TEST BMG enterprise2/U
    discountGroupDetails: true/0/true/S
    invoiceOptionDetails: GF EXCLUSION/false/1/0/D
    contractInformationDetails: Q.ADVAN M/5000/599999/3/16/2015/123456/Y/12
    salesInformationDetails: AC/SOV1/Automated Order
    billingAccountDetails: Sic/0/LTL/false/true/BF/CO/CA/0/true
    createOrderDetails: SUBMIT/pctl/BMG/b7cab119-5d9c-4ddc-ad4d-e016951ece8f/N/BMG/704883/52559143/52559143/10432921
    loggedUserDetails: testEnterprise2@centurylink.com/name/3039925648
    arrayOfString: 123456
    aateConstants: 10760263/87850143/LATIS/false
    getAccountsConstants: 0/0

eureka:
  instance:
    nonSecurePort: 80
    hostname: ${vcap.application.uris[0]}
  client:
    service-url:
      defaultZone: ${vcap.services.eureka.credentials.url}
redis:
    cacheHost: ${vcap.services.redis.credentials.host}
    cachePort: ${vcap.services.redis.credentials.port}
    cacheExpiration: 300 #Seconds
jwt:
    tokenExpirationTime: 2592000 # Number of minutes
    refreshTokenExpTime: 2592000 # Minutes
    tokenIssuer: Ctl
    tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
    publicKey: apiclient@ctl.com
url:
    userAdminServiceUrl: https://ecaps-test1.foss.dev.qintra.com:443/ecaps/service/UserAdminService
    accountServiceUrl: https://cxg7i.test.intranet/itv1/ecaps/service/AccountService
    enterpriseAdminService: https://cxg7i.test.intranet/itv1/ecaps/service/EnterpriseAdminService
    qcsetupSFAWS: http://qcsetup-itv1.dev.qintra.com/webservice/qcsetupSFAWS
    password: cGN0bDpPcmFuZ2VmZWF0aGVycyQk

camel:
    configFilePath: camel/camel-binding-prod-config.xml
#account:
#    userAuthString: PASSWORD/pctl/EMPLOYEE/Orangefeathers$$/pctl/EMPLOYEE
#    enterPriseDetails: false/BMG/testEnterprise2@hotmail.com/TEST BMG enterprise2/U
