# EMBEDDED SERVER CONFIGURATION
spring:
  profiles: prod
  address:
    clientId: GeoDevTest
    webService: REST
    postalRestUrl: https://cxg7i.test.intranet/itv1/api/v1/postalAddresses/validations
    civicRestUrl: https://cxg7i.test.intranet/itv1/api/v1/civicAddresses/validations
    authorization: Basic cGN0bDpPcmFuZ2VmZWF0aGVycyQk
camel:
    configFilePath: camel/camel-binding-prod-config.xml
