# EMBEDDED SERVER CONFIGURATION
spring:
  data:
    mongodb.host: ${vcap.services.mongodb.credentials.host}
    mongodb.port: ${vcap.services.mongodb.credentials.port}
    mongodb.uri: ${vcap.services.mongodb.credentials.uri}
eureka:
  instance:
    nonSecurePort: 80
    hostname: ${vcap.services.eureka.credentials.host}
  client:
    service-url:
      defaultZone: ${vcap.services.eureka.credentials.url}
camel:
    configFilePath: camel/camel-binding-config.xml
