# EMBEDDED SERVER CONFIGURATION
spring:
  data:
    mongodb.host: ${vcap.services.mongodb.credentials.host}
    mongodb.port: ${vcap.services.mongodb.credentials.port}
    mongodb.uri: ${vcap.services.mongodb.credentials.uri}
  address:
    clientId: GeoDevTest
    webService: REST
    restAddressUrl: https://cxg7i.test.intranet/itv1/api/v1/postalAddresses/validations
    authorization: Basic cGN0bDpPcmFuZ2VmZWF0aGVycyQk
eureka:
  instance:
    nonSecurePort: 80
    hostname: ${vcap.application.uris[0]}
  client:
    service-url:
      defaultZone: ${vcap.services.eureka.credentials.url}
camel:
    configFilePath: camel/camel-binding-config.xml
