# EMBEDDED SERVER CONFIGURATION
server:
    port: ${port:8087}
    context-path: /
    error.whitelabel.enabled: false
    compression:
      enabled: true
      min-response-size: 1024
      mime-types:
          - text/html
          - text/css
          - text/plain
          - text/xml
          - application/json
          - application/javascript

# JACKSON
spring:
    jackson.serialization:
        write_dates_as_timestamps: false
    data:
      mongodb.host: localhost
      mongodb.port: 27017
      mongodb.uri: mongodb://localhost/pctl
    activemq:
      broker-url: tcp://DS-FKXNWQ1:61616
      user-queue: com.ctl.user.queue
      cart-queue: com.ctl.cart.queue
      order-queue: com.ctl.order.queue
      sfaint-queue: com.ctl.sfaint.queue
      default-queue: com.ctl.default.queue
jwt:
    tokenExpirationTime: 2592000 # Number of minutes
    refreshTokenExpTime: 2592000 # Minutes
    tokenIssuer: Ctl
    tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
    publicKey: apiclient@ctl.com
    header: Authorization
    route:
      authentication:
        path: auth
redis:
    cacheHost: DS-FKXNWQ1 # Host name
    cachePort: 6379 # port number
    cacheExpiration: 300 #Seconds

security:
  basic:
    enabled: false

# EUREKA
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true

---

spring:
  profiles: docker
  data:
    mongodb.host: localhost
    mongodb.port: 27017
    mongodb.uri: mongodb://localhost/pctl
  activemq:
    broker-url: tcp://DS-FKXNWQ1:61616
    user-queue: com.ctl.user.queue
    cart-queue: com.ctl.cart.queue
    order-queue: com.ctl.order.queue
    sfaint-queue: com.ctl.sfaint.queue
    default-queue: com.ctl.default.queue

jwt:
    tokenExpirationTime: 2592000 # Number of minutes
    refreshTokenExpTime: 2592000 # Minutes
    tokenIssuer: Ctl
    tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
    publicKey: apiclient@ctl.com
    header: Authorization
    route:
      authentication:
        path: auth

# EUREKA
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8081/eureka/

redis:
  cacheHost: DS-FKXNWQ1 # Host name
  cachePort: 6379 # port number
  cacheExpiration: 300 #Seconds

---


spring:
  profiles: standalone
  data:
    mongodb.host: localhost
    mongodb.port: 27017
    mongodb.uri: mongodb://localhost/pctl
  activemq:
    broker-url: tcp://DS-FKXNWQ1:61616
    user-queue: com.ctl.user.queue
    cart-queue: com.ctl.cart.queue
    order-queue: com.ctl.order.queue
    sfaint-queue: com.ctl.sfaint.queue
    default-queue: com.ctl.default.queue

jwt:
    tokenExpirationTime: 2592000 # Number of minutes
    refreshTokenExpTime: 2592000 # Minutes
    tokenIssuer: Ctl
    tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
    publicKey: apiclient@ctl.com

redis:
    cacheHost: DS-FKXNWQ1 # Host name
    cachePort: 6379 # port number
    cacheExpiration: 300 #Seconds

# EUREKA
eureka:
  instance:
    hostname: localhost
    port: 8081
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

---

# EMBEDDED SERVER CONFIGURATION
spring:
  profiles: ssl
server:
    ssl:
      key-store: classpath:keystore.p12
      key-store-password: password
      keyStoreType: PKCS12
      key-password: password
      keyAlias: tomcat

---

spring:
  profiles: cloud
  data:
    mongodb.host: ${vcap.services.mongodb.credentials.host}
    mongodb.port: ${vcap.services.mongodb.credentials.port}
    mongodb.uri: ${vcap.services.mongodb.credentials.uri}
  activemq:
    broker-url: ${vcap.services.activemq.credentials.uri}
    user-queue: ${vcap.services.activemq.credentials.user.queue}
    cart-queue: ${vcap.services.activemq.credentials.cart.queue}
    order-queue: ${vcap.services.activemq.credentials.order.queue}
    notification-queue: ${vcap.services.activemq.credentials.notification.queue}
    account-queue: ${vcap.services.activemq.credentials.account.queue}
    sfaint-queue: ${vcap.services.activemq.credentials.sfaint.queue}
    default-queue: ${vcap.services.activemq.credentials.default.queue}
    
eureka:
  instance:
    nonSecurePort: 80
    hostname: ${vcap.services.eureka.credentials.host}
  client:
    service-url:
      defaultZone: ${vcap.services.eureka.credentials.url}

redis:
    cacheHost: ${vcap.services.redis.credentials.host}
    cachePort: ${vcap.services.redis.credentials.port}
    cacheExpiration: 300 #Seconds

jwt:
    tokenExpirationTime: 2592000 # Number of minutes
    refreshTokenExpTime: 2592000 # Minutes
    tokenIssuer: Ctl
    tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
    publicKey: apiclient@ctl.com
