# EMBEDDED SERVER CONFIGURATION
server:
    port: ${port:8086}
    context-path: /
    error.whitelabel.enabled: false
    compression:
      enabled: true
      min-response-size: 1024
      mime-types:
          - text/html
          - text/css
          - text/plain
          - text/xml
          - application/json
          - application/javascript
# JACKSON
spring:
    jackson.serialization:
        write_dates_as_timestamps: false
    data:
      mongodb.host: localhost
      mongodb.port: 27017
      mongodb.uri: mongodb://localhost/pctl
jwt:
    tokenExpirationTime: 2592000 # Number of minutes
    refreshTokenExpTime: 2592000 # Minutes
    tokenIssuer: Ctl
    tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
    publicKey: apiclient@ctl.com
    header: Authorization
    route:
      authentication:
        path: auth


# EUREKA
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true




---

spring:
  profiles: docker
  data:
    mongodb.host: localhost
    mongodb.port: 27017
    mongodb.uri: mongodb://localhost/pctl

jwt:
    tokenExpirationTime: 2592000 # Number of minutes
    refreshTokenExpTime: 2592000 # Minutes
    tokenIssuer: Ctl
    tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
    publicKey: apiclient@ctl.com
    header: Authorization
    route:
      authentication:
        path: auth

# EUREKA
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8081/eureka/


---

spring:
  profiles: standalone
  data:
    mongodb.host: localhost
    mongodb.port: 27017
    mongodb.uri: mongodb://localhost/pctl

jwt:
    tokenExpirationTime: 2592000 # Number of minutes
    refreshTokenExpTime: 2592000 # Minutes
    tokenIssuer: Ctl
    tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
    publicKey: apiclient@ctl.com
    header: Authorization
    route:
      authentication:
        path: auth

# EUREKA
eureka:
  instance:
    hostname: localhost
    port: 8081
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

