# EMBEDDED SERVER CONFIGURATION
spring:
  data:
    mongodb.host: localhost
    mongodb.port: 27017
    mongodb.uri: mongodb://localhost/pctl
    mail:
      host: localhost
      port: 25
      username: d4c84030201b3b
      password: 96eb7582df3e1b
      properties:
        mail:
          smtp:
            auth: false
            ssl:
              enable: true
            starttls:
              enable: false
              required: false
    activemq:
      broker-url: tcp://DS-FKXNWQ1:61616
      user-queue: com.ctl.user.queue
      cart-queue: com.ctl.cart.queue
      order-queue: com.ctl.order.queue
      notification-queue: com.ctl.notification.queue
      account-queue: com.ctl.account.queue
      sfaint-queue: com.ctl.sfaint.queue
      default-queue: com.ctl.default.queue

jwt:
    tokenExpirationTime: 2592000 # Number of minutes
    refreshTokenExpTime: 2592000 # Minutes
    tokenIssuer: Ctl
    tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
    publicKey: apiclient@ctl.com


redis:
    cacheHost: DS-JZWNWQ1 # Host name
    cachePort: 6379 # port number
    cacheExpiration: 300 #Seconds

# EUREKA
eureka:
  instance:
    hostname: localhost
    port: 8081
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
