# EMBEDDED SERVER CONFIGURATION
spring:
  profiles: prod
camel:
    configFilePath: camel/camel-binding-prod-config.xml
url:
    reserveOrderIdUrl: http://ordering-e2e.dev.qintra.com:80/OaWSLite/OaWSLite
