# EMBEDDED SERVER CONFIGURATION
server:
    port: ${port:8088}
    context-path: /
    error.whitelabel.enabled: false
    compression:
      enabled: true
      min-response-size: 1024
      mime-types:
          - text/html
          - text/css
          - text/plain
          - text/xml
          - application/json
          - application/javascript
# JACKSON
spring:
    jackson.serialization:
        write_dates_as_timestamps: false
    data:
      mongodb.host: localhost
      mongodb.port: 27017
      mongodb.uri: mongodb://localhost/pctl
    activemq:
      broker-url: tcp://DS-FKXNWQ1:61616
      user-queue: com.ctl.user.queue
      cart-queue: com.ctl.cart.queue
      order-queue: com.ctl.order.queue
      sfaint-queue: com.ctl.sfaint.queue
      notification-queue: com.ctl.notification.queue
      account-queue: com.ctl.account.queue
      default-queue: com.ctl.default.queue
    service:
      product-service:
          url: ${vcap.services.config.credentials.zuul.product.url}

jwt:
    tokenExpirationTime: 2592000 # Number of minutes
    refreshTokenExpTime: 2592000 # Minutes
    tokenIssuer: Ctl
    tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
    publicKey: apiclient@ctl.com

redis:
    cacheHost: DS-FKXNWQ1 # Host name
    cachePort: 6379 # port number
    cacheExpiration: 300 #Seconds

security:
  basic:
    enabled: false

# EUREKA
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true

order:
    restUrl: http://qtomavmdt362.dev.qintra.com:7003/PoimOrderFlow/PoimService/RestServiceforPortal/processPortalOrder

---

spring:
  profiles: docker
  data:
    mongodb.host: localhost
    mongodb.port: 27017
    mongodb.uri: mongodb://localhost/pctl
  activemq:
    broker-url: tcp://DS-FKXNWQ1:61616
    user-queue: com.ctl.user.queue
    cart-queue: com.ctl.cart.queue
    order-queue: com.ctl.order.queue
    sfaint-queue: com.ctl.sfaint.queue
    notification-queue: com.ctl.notification.queue
    account-queue: com.ctl.account.queue
    default-queue: com.ctl.default.queue

jwt:
    tokenExpirationTime: 2592000 # Number of minutes
    refreshTokenExpTime: 2592000 # Minutes
    tokenIssuer: Ctl
    tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
    publicKey: apiclient@ctl.com


# EUREKA
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8081/eureka/
camel:
    configFilePath: camel/camel-binding-config.xml

redis:
    cacheHost: DS-FKXNWQ1 # Host name
    cachePort: 6379 # port number
    cacheExpiration: 300 #Seconds

---

spring:
  profiles: standalone
  data:
    mongodb.host: localhost
    mongodb.port: 27017
    mongodb.uri: mongodb://localhost/pctl
  activemq:
    broker-url: tcp://DS-FKXNWQ1:61616
    user-queue: com.ctl.user.queue
    cart-queue: com.ctl.cart.queue
    order-queue: com.ctl.order.queue
    notification-queue: com.ctl.notification.queue
    account-queue: com.ctl.account.queue
    sfaint-queue: com.ctl.sfaint.queue
    default-queue: com.ctl.default.queue

jwt:
    tokenExpirationTime: 2592000 # Number of minutes
    refreshTokenExpTime: 2592000 # Minutes
    tokenIssuer: Ctl
    tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
    publicKey: apiclient@ctl.com

redis:
    cacheHost: DS-FKXNWQ1 # Host name
    cachePort: 6379 # port number
    cacheExpiration: 300 #Seconds

# EUREKA
eureka:
  instance:
    hostname: localhost
    port: 8081
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

camel:
    configFilePath: camel/camel-binding-config.xml

order:
    restUrl: http://qtomavmdt362.dev.qintra.com:7003/PoimOrderFlow/PoimService/RestServiceforPortal/processPortalOrder
---

spring:
  profiles: cloud
  data:
    mongodb.host: ${vcap.services.mongodb.credentials.host}
    mongodb.port: ${vcap.services.mongodb.credentials.port}
    mongodb.uri: ${vcap.services.mongodb.credentials.uri}
  activemq:
    broker-url: ${vcap.services.activemq.credentials.uri}
    user-queue: ${vcap.services.activemq.credentials.user.queue}
    cart-queue: ${vcap.services.activemq.credentials.cart.queue}
    order-queue: ${vcap.services.activemq.credentials.order.queue}
    notification-queue: ${vcap.services.activemq.credentials.notification.queue}
    account-queue: ${vcap.services.activemq.credentials.account.queue}
    sfaint-queue: ${vcap.services.activemq.credentials.sfaint.queue}
    default-queue: ${vcap.services.activemq.credentials.default.queue}
  service:
    product-service:
        url: ${vcap.services.config.credentials.zuul.product.url}


eureka:
  instance:
    nonSecurePort: 80
    hostname: ${vcap.application.uris[0]}
  client:
    service-url:
      defaultZone: ${vcap.services.eureka.credentials.url}

camel:
    configFilePath: camel/camel-binding-cloud-config.xml

redis:
    cacheHost: ${vcap.services.redis.credentials.host}
    cachePort: ${vcap.services.redis.credentials.port}
    cacheExpiration: 300 #Seconds

jwt:
    tokenExpirationTime: 2592000 # Number of minutes
    refreshTokenExpTime: 2592000 # Minutes
    tokenIssuer: Ctl
    tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
    publicKey: apiclient@ctl.com

order:
    #restUrl: http://qtomavmdt362.dev.qintra.com:7003/PoimOrderFlow/PoimService/RestServiceforPortal/processPortalOrder
    restUrl: https://cxg7i.test.intranet/itv1/PoimOrderFlow/PoimService/RestServiceforPortal/processPortalOrder
    authorization: Basic cGN0bDpPcmFuZ2VmZWF0aGVycyQk

---

spring:
  profiles: prod
camel:
    configFilePath: camel/camel-binding-prod-config.xml
url:
    reserveOrderIdUrl: http://ordering-e2e.dev.qintra.com:80/OaWSLite/OaWSLite
