# EMBEDDED SERVER CONFIGURATION
spring:
  profiles: prod
  data:
    mongodb.host: ${vcap.services.mongodb.credentials.host}
    mongodb.port: ${vcap.services.mongodb.credentials.port}
    mongodb.uri: ${vcap.services.mongodb.credentials.uri}
  activemq:
    broker-url: ${vcap.services.activemq.credentials.uri}
    user-queue: ${vcap.services.activemq.credentials.user.queue}
    cart-queue: ${vcap.services.activemq.credentials.cart.queue}
    order-queue: ${vcap.services.activemq.credentials.order.queue}
    notification-queue: ${vcap.services.activemq.credentials.notification.queue}
    account-queue: ${vcap.services.activemq.credentials.account.queue}
    sfaint-queue: ${vcap.services.activemq.credentials.sfaint.queue}
    default-queue: ${vcap.services.activemq.credentials.default.queue}
  service:
    product-service:
        url: ${vcap.services.config.credentials.zuul.product.url}


eureka:
  instance:
    nonSecurePort: 80
    hostname: ${vcap.application.uris[0]}
  client:
    service-url:
      defaultZone: ${vcap.services.eureka.credentials.url}

camel:
    configFilePath: camel/camel-binding-prod-config.xml

redis:
    cacheHost: ${vcap.services.redis.credentials.host}
    cachePort: ${vcap.services.redis.credentials.port}
    cacheExpiration: 300 #Seconds

jwt:
    tokenExpirationTime: 2592000 # Number of minutes
    refreshTokenExpTime: 2592000 # Minutes
    tokenIssuer: Ctl
    tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
    publicKey: apiclient@ctl.com

order:
    #restUrl: http://qtomavmdt362.dev.qintra.com:7003/PoimOrderFlow/PoimService/RestServiceforPortal/processPortalOrder
    restUrl: https://cxg7i.test.intranet/itv1/PoimOrderFlow/PoimService/RestServiceforPortal/processPortalOrder
    authorization: Basic cGN0bDpPcmFuZ2VmZWF0aGVycyQk
