# EMBEDDED SERVER CONFIGURATION
spring:
  data:
    mongodb.host: localhost
    mongodb.port: 27017
    mongodb.uri: mongodb://localhost/pctl

jwt:
    tokenExpirationTime: 2592000 # Number of minutes
    refreshTokenExpTime: 2592000 # Minutes
    tokenIssuer: Ctl
    tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
    publicKey: apiclient@ctl.com
    header: Authorization
    route:
      authentication:
        path: auth

redis:
    cacheHost: DS-FKXNWQ1 # Host name
    cachePort: 6379 # port number
    cacheExpiration: 300 #Seconds



# EUREKA
eureka:
  instance:
    hostname: localhost
    port: 8081
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

camel:
    configFilePath: camel/test-camel-binding-config.xml

price:
    restUrl: https://cxg7i.test.intranet/int2/GetPriceSvc
    authorization: Basic cG9ydGFsQ3hnNzo1ZEhyOGlEeUxwdXExSklVakZnRV4=
