# EMBEDDED SERVER CONFIGURATION
spring:
  profiles: prod
sfaint:
    createleadurl: https://qxgsfa-e2e.foss.dev.qintra.com/qxgsfa/servicesSec/platformCtlCreateLead
    createsfaccounturl: https://qxgsfa-e2e.foss.dev.qintra.com/qxgsfa/servicesSec/platformCtlCreateAccount
    createOppurtunityurl: https://qxgsfa-e2e.foss.dev.qintra.com/qxgsfa/servicesSec/platformCtlCreateOppty
    creditcheckurl: https://qxgsfa-e2e.foss.dev.qintra.com/qxgsfa/servicesSec/platformCtlRequestCreditCheck
    customerlookupurl: https://qxgsfa-e2e.foss.dev.qintra.com/qxgsfa/servicesSec/platformCtlLookupCustomer
