# EMBEDDED SERVER CONFIGURATION
spring:
  profiles: release
sfaint:
    createleadurl: https://qxgsfa.foss.qintra.com/qxgsfa/servicesSec/platformCtlCreateLead
    createsfaccounturl: https://qxgsfa.foss.qintra.com/qxgsfa/servicesSec/platformCtlCreateAccount
    createOppurtunityurl: https://qxgsfa.foss.qintra.com/qxgsfa/servicesSec/platformCtlCreateOppty
    creditcheckurl: https://qxgsfa.foss.qintra.com/qxgsfa/servicesSec/platformCtlRequestCreditCheck
    customerlookupurl: https://qxgsfa.foss.qintra.com/qxgsfa/servicesSec/platformCtlLookupCustomer
    platformCreateOrderUrl: https://qxgsfa.foss.qintra.com/qxgsfa/servicesSec/platformCtlCreateOrder

