# EMBEDDED SERVER CONFIGURATION
server:
    port: ${port:8083}
    context-path: /
    error.whitelabel.enabled: false
    compression:
      enabled: true
      min-response-size: 1024
      mime-types:
          - text/html
          - text/css
          - text/plain
          - text/xml
          - application/json
          - application/javascript
# JACKSON
spring:
    jackson.serialization:
        write_dates_as_timestamps: false
    data:
      mongodb.host: localhost
      mongodb.port: 27017
      mongodb.uri: mongodb://localhost/pctl

jwt:
    tokenExpirationTime: 5184000 # Number of minutes
    refreshTokenExpTime: 5184000 # Minutes
    tokenIssuer: Ctl
    tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
    publicKey: apiclient@ctl.com
    header: Authorization
    route:
      authentication:
        path: auth

activemq:
    broker-url: tcp://localhost:61616
    user: "admin"
    password: "admin"
    pooled: false
    destinationQueue: "com.ctl.queue"

# EUREKA
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true



# Disable spring basic authentication security
#security:
#  basic:
#    enabled: false
#  oauth2:
#    resource:
#      jwt:
#        keyValue: |
#              -----BEGIN PUBLIC KEY-----
#              MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
#              -----END PUBLIC KEY-----
#      id: openid
#      serviceId: ${PREFIX:}resource
# LOGGING
#logging.level.org.springframework.security: DEBUG

---

spring:
  profiles: docker
  data:
    mongodb.host: localhost
    mongodb.port: 27017
    mongodb.uri: mongodb://localhost/pctl

jwt:
    tokenExpirationTime: 5184000 # Number of minutes
    refreshTokenExpTime: 5184000 # Minutes
    tokenIssuer: Ctl
    tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
    publicKey: apiclient@ctl.com
    header: Authorization
    route:
      authentication:
        path: auth

activemq:
    broker-url: tcp://localhost:61616
    user: "admin"
    password: "admin"
    pooled: false
    destinationQueue: "com.ctl.queue"

# EUREKA
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8081/eureka/


---

spring:
  profiles: standalone
  data:
    mongodb.host: localhost
    mongodb.port: 27017
    mongodb.uri: mongodb://localhost/pctl

jwt:
    tokenExpirationTime: 5184000 # Number of minutes
    refreshTokenExpTime: 5184000 # Minutes
    tokenIssuer: Ctl
    tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
    publicKey: apiclient@ctl.com
    header: Authorization
    route:
      authentication:
        path: auth

activemq:
    broker-url: tcp://localhost:61616
    user: "admin"
    password: "admin"
    pooled: false
    destinationQueue: "com.ctl.queue"

# EUREKA
eureka:
  instance:
    hostname: localhost
    port: 8081
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

